# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: acrAmaris-conn
        repository: testRepo
        tags: |
          $(tag)
    - task: HelmDeploy@0
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Azure Pass - Sponsorship (73c12a5d-dd45-4dd6-8765-7a2eb5731a31)'
        azureResourceGroup: 'devops-rg'
        kubernetesCluster: 'aks-amaris'
        command: 'init'
        arguments: '--client-only'
    - task: HelmDeploy@0
      inputs:
        azureSubscription: 'Azure Pass - Sponsorship (73c12a5d-dd45-4dd6-8765-7a2eb5731a31)'
        azureResourceGroup: 'devops-rg'
        kubernetesCluster: 'aks-amaris'
        useClusterAdmin: true
        command: 'package'
        chartPath: './test'